

const CODEGEN_CLIENT_GET_REQUEST = 'CODEGEN_CLIENT_GET_REQUEST';
const CODEGEN_CLIENT_GET_RESPONSE = 'CODEGEN_CLIENT_GET_RESPONSE';
const CODEGEN_CLIENT_GET_FAILURE = 'CODEGEN_CLIENT_GET_FAILURE';

const CODEGEN_SERVER_GET_REQUEST = 'CODEGEN_SERVER_GET_REQUEST';
const CODEGEN_SERVER_GET_RESPONSE = 'CODEGEN_SERVER_GET_RESPONSE';
const CODEGEN_SERVER_GET_FAILURE = 'CODEGEN_SERVER_GET_FAILURE';

const codegenClientGetActionsTypes = [
  CODEGEN_CLIENT_GET_REQUEST,
  CODEGEN_CLIENT_GET_RESPONSE,
  CODEGEN_CLIENT_GET_FAILURE,
];

const codegenServerGetActionsTypes = [
  CODEGEN_SERVER_GET_REQUEST,
  CODEGEN_SERVER_GET_RESPONSE,
  CODEGEN_SERVER_GET_FAILURE,
];


export const ActionsTypes =  {
  CODEGEN_CLIENT_GET_REQUEST,
  CODEGEN_CLIENT_GET_RESPONSE,
  CODEGEN_CLIENT_GET_FAILURE,
  codegenClientGetActionsTypes,
  CODEGEN_SERVER_GET_REQUEST,
  CODEGEN_SERVER_GET_RESPONSE,
  CODEGEN_SERVER_GET_FAILURE, 
  codegenServerGetActionsTypes 
};
